runtime:
  robot: rviz
  capture: webapp
  move_seconds: 1.2
  capture_seconds: 0.2
  person_sensor: mediapipe
  camera_index: 0
  debug_window: true

web:
  host: 0.0.0.0
  port: 8443
  ssl_keyfile: certs/key.pem
  ssl_certfile: certs/cert.pem
